### ISSUE TITLE
Add license accounts

### ISSUE THREAD

**Issue by somucheffort** [matelauncher/mate-react#1]
Currently, MATE supports only pirate accounts. This needs to be implemented.

**Comment by redcarti** [comment]
Account will have these properties:

```typescript
interface Account {
    type: 'pirate' | 'license';
    nickname?: string; // pirate accounts
    uuid?: string; // license accounts
    credentials?: { // same as uuid
        email: string;
        password: string;
    }
}
```

- [ ] Implemented

* * *

After some research I thought about getting nickname from UUID but... same as #3 if there's no internet connection you can't get info... 
Offline player uses `OfflinePlayer:nickname` scheme to set UUID but... what's with license accounts...

**Comment by redcarti** [comment]
If no internet connection, get nickname every time as enter launcher.

**Comment by somucheffort** [comment]
uhhh, i'll close it but i dont remember did i make some changes to it
