### ISSUE TITLE
Add full i18n

### ISSUE THREAD

**Issue by somucheffort** [matelauncher/mate-react#4]
There are implemented languages:
- Russian
- English
- Ukrainian 
- Kazakh
- Latvian 
- German 

And languages for fun:
- Kolya's Language
- Frayz's Language
- Cartinese

But for now enabled only Russian language and English as a fallback.
Needs to be implemented but it's connected to #2 (adding settings page).

**Comment by redcarti** [comment]
- [x] Launcher languages
- [ ] RPC languages

**Comment by somucheffort** [comment]
its done, idk why didnt i close this...
